ecommerce-books-store-master/Books/Areas/Admin/Controllers/CoverController.cs
using Books.Domain.Entities;
using Books.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Books.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CoverController : Controller
    {
        private readonly IUnitOfWork<Cover> _cover;

        public CoverController(IUnitOfWork<Cover> cover)
        {
            _cover = cover;
        }

        // GET: CoverController
        public async Task<ActionResult> Index()
        {
            IEnumerable<Cover> covers = await _cover.Entity.GetAllAsync();
            return View(covers);
        }

        // GET: CoverController/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CoverController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Cover cover)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _cover.Entity.InsertAsync(cover);
                    await _cover.CompleteAsync();
                    TempData["Success"] = "Cover created successfully.";
                    return RedirectToAction(nameof(Index));
                }
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "An Expected Error!");
            }

            return View();
        }

        // GET: CoverController/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var cover = await _cover.Entity.GetFirstOrDefaultAsync(c => c.Id == id);
            if (cover == null)
            {
                return NotFound();
            }

            return View(cover);
        }

        // POST: CoverController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Cover cover)
        {
            if (id != cover.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _cover.Entity.UpdateAsync(cover);
                    await _cover.CompleteAsync();
                    TempData["Success"] = "Category upaded successfully.";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (await CoverExists(cover.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cover);
        }


        // GET: CoverController/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cover = await _cover.Entity.GetFirstOrDefaultAsync(c => c.Id == id);
            if (cover == null)
            {
                return NotFound();
            }

            return View(cover);
        }

        // POST: CoverController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var cover = await _cover.Entity.GetByIdAsync(id);
                await _cover.Entity.DeleteAsync(cover.Id);
                await _cover.CompleteAsync();
                TempData["Success"] = "Category deleted successfully.";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        private async Task<bool> CoverExists(int id)
        {
            return await _cover.Entity.ExistsAsync(id);
        }
    }
}

ecommerce-books-store-master/Books/Areas/Admin/Views/Cover/Create.cshtml
@model Books.Domain.Entities.Cover

@{
    ViewData["Title"] = "Create";
}

<h1>Create Cover</h1>

 <hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Save" class="btn btn-primary" />
                <button asp-action="Index" class="btn btn-secondary">Back to list</button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}
 

ecommerce-books-store-master/Books/Areas/Admin/Views/Cover/Delete.cshtml
@model Books.Domain.Entities.Cover

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this Cover?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <button asp-action="Index" class="btn btn-secondary">Back to list</button>
     </form>
</div>

ecommerce-books-store-master/Books/Areas/Admin/Views/Cover/Edit.cshtml
@model Books.Domain.Entities.Cover

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Cover</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Save" class="btn btn-primary" />
                <button asp-action="Index" class="btn btn-secondary">Back to list</button>
            </div>
        </form>
    </div>
</div>
 
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

ecommerce-books-store-master/Books/Areas/Admin/Views/Cover/Index.cshtml
 @model IEnumerable<Books.Domain.Entities.Cover>
@{
    ViewData["Title"] = "Index";
    #pragma warning disable 
}

 <div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Covers</h2>
        </div>
        <div class="col-6 text-end">
            <a class="btn btn-primary" asp-controller="Cover" asp-action="Create">
                <i class="bi bi-plus-circle"></i> &nbsp; New</a>
        </div>
    </div>
    <br>
    <table class="table table-striped table-hover w-100" >
        <thead>
            <tr>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var cover in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => cover.Name)
                    </td>
                    <td colspan="2" class="text-end">
                        <a class="btn btn-info mx-2"asp-controller="Cover" asp-action="Edit" asp-route-id="@cover.Id"
                        > <i class="bi bi-pencil-square"></i> Edit</a>
                        <a class="btn btn-danger mx-2"asp-controller="Cover" asp-action="Delete" asp-route-id="@cover.Id"
                        > <i class="bi bi-trash-fill"></i> Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>